### ISSUE TITLE
[Sample] `daysSinceOnsetOfSymptoms`をサーバーに必ず送る

### ISSUE THREAD

**Issue by keiji** [keiji/chino#108]
https://github.com/cocoa-mhlw/cocoa/discussions/334#discussioncomment-1213017 に関連。

`days_since_onset_of_symptoms` について対応する上で、当初 https://github.com/keiji/en-calibration-server/pull/2 で、症状が出ていないなどの理由で症状発生日が確定できないときに、`daysSinceOnsetOfSymptoms`のキーを値`DAYS_SINCE_ONSET_OF_SYMPTOMS_UNKNOWN`（`2147483647`）として扱うようにしていた。

（iOSで規定されている`ENDaysSinceOnsetOfSymptomsUnknown`はlong値の最大値であるため、int型のAndroidでは設定できない。そのため、Android側の値に合わせる形とした経緯がある）

この方法はiOSであれば問題なかったが`InfectiousnessWhenDaysSinceOnsetMissing`の取り扱いとなった。一方、Androidでは接触確認の結果が返されない事象が発生した。

`days_since_onset_of_symptoms`の値に想定されている(`-14`から`14`)までの範囲を設定して再テストしたところ、問題なく接触確認処理が行われ、結果を受け取ることができた。
このことから、Android版において`days_since_onset_of_symptoms`に設定する値は`-14`から`14`の範囲でなければならないと言う制約があるものと推測する。

AndroidとiOSの仕様差を吸収するため、`daysSinceOnsetOfSymptoms`必ずサーバーに送るようにする。サンプルアプリでは症状発生日の入力項目を設けていないので、取得できたTEKに適切な数値を設定して対応とする。

**Comment by tmurakami** [comment]
`days_since_onset_of_symptoms` が存在しない TEK (旧フォーマットの TEK) を `provideDiagnosiskeys()`/`detectExposures()` に与えたときの `ExposureWindow.getInfectiousness()`/`ENExposureWindow.infectiousness`  の結果はどのようになりますでしょうか？
