### ISSUE TITLE
[Android] ExposureStateBroadcastReceiver の状態を考慮する

### ISSUE THREAD

**Issue by tmurakami** [keiji/chino#78]
ExposureStateBroadcastReceiver について、`OnReceive`内で呼び出している各タスクは`OnReceive`を抜けた後も処理を続けることになるのだと思うのですが、 その場合以下にあるようにシステムによってアプリプロセスを終了させられてしまう可能性があるのではないかと思います。
(見落としならばすみません)
https://developer.android.com/guide/components/broadcasts?hl=ja#effects-process-state

例えば Google のサンプルでは、WorkManager を使っています。
https://github.com/google/exposure-notifications-android/blob/610788eb3815d8ddb397332ba6f982308f7cde01/app/src/main/java/com/google/android/apps/exposurenotification/nearby/ExposureNotificationBroadcastReceiver.java#L66
https://github.com/google/exposure-notifications-android/blob/610788eb3815d8ddb397332ba6f982308f7cde01/app/src/main/java/com/google/android/apps/exposurenotification/nearby/StateUpdatedWorker.java#L117

`Xamarin.ExposureNotification`では JobIntentService にまかせています。
https://github.com/xamarin/XamarinComponents/blob/e5ac2d06c8b6b2904ff119d8bae8b1d5e7cb2127/XPlat/ExposureNotification/source/Xamarin.ExposureNotification/CallbackService.android.cs#L28
https://github.com/xamarin/XamarinComponents/blob/main/XPlat/ExposureNotification/source/Xamarin.ExposureNotification/CallbackService.android.cs#L39

**Comment by keiji** [comment]
ありがとうございます。ご指摘のようにBroadcastReceiverがシステムより停止する可能性を見落としていました。
現状、2つの方法で解決を模索しています。

一つはBroadcastReceiverの`GoAsync`を呼び出すことで非同期処理が行われているとシステムに知らせることで停止を回避する方法（ #80 ）です。
基本的に、接触確認APIの該当処理は「データを永続化して通知」という限定的な処理であり、詳細は後述しますがJobSchedulerやWorkManagerにつなぐのであれば、ライブラリを使うアプリ側でやって欲しいと考えており、こちらを推していきたい気持ちです。

二つ目は`GoAsync`に加えて、JobSchedulerを使う方法（ #81 ）です。
`JobIntentService`はAndroid 8.0（Oreo）からDeprecatedなので、`JobService`を使う方法にしています。この方法だとパラメーターを`PersistableBundle`で渡さなければなりません。今回はJSONにシリアライズして文字列で渡しています。これは大変に不本意な方法です。

接触情報についてはJobServiceの中からENにアクセスする試みもあります（ https://github.com/keiji/chino/commit/cfc7ffba9f9aeac8f0d9fb12d5a88647b418ea67 ）。しかし、この場合もPreAuthorized APIの結果はIntentから取得するのでシリアライズが必要なくなることはなりそうです。

同様の処理を行う場合、データ自体は速やかに永続化して、`JobService`（WorkManager）に処理対象のIDをパラメーターで渡す。`JobService`からは永続化されたデータを読むだけという書き方をしています。シリアライズするにしても、永続化するにしても、その辺りの実装はアプリに任せて、ライブラリとしては手を出さない方が良いだろうと考えています。

**Comment by tmurakami** [comment]
> BroadcastReceiverのGoAsyncを呼び出す

`GoAsync()`による解決は難しいかもしれません。

https://developer.android.com/reference/android/content/BroadcastReceiver?hl=en#goAsync()
には

> However, once you use goAsync, though able to be off the main thread, the broadcast execution limit still applies, and that includes the time spent between calling this method and ultimately PendingResult.finish().

とあり、当該メソッドを使ったとしても BroadcastReceiver の 10 秒制限は突破できないのではないかと思っています。

`provideDiagnosisKeys()`以外の API のタイムアウトは 2 分
https://developers.google.cn/android/exposure-notifications/release-notes?hl=en#api_call_timeouts
で、端末スペック等によっては`GetDailySummariesAsync()`等の処理に 10 秒以上かかってしまうこともありえそうなので、`GoAsync()`では厳しい気がしています。

> この場合もPreAuthorized APIの結果はIntentから取得するのでシリアライズが必要なくなることはなりそうです。

`requestPreAuthorizedTemporaryExposureKeyRelease()`の結果を受けとるケースについてですが、ドイツのアプリでは`registerReceiver()`で BroadcastReceiver を AppContext に登録して
https://github.com/corona-warn-app/cwa-app-android/blob/66055425822758f2575de50d7e82b371bb81370c/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/nearby/modules/tekhistory/DefaultTEKHistoryProvider.kt#L174

ここで await している
https://github.com/corona-warn-app/cwa-app-android/blob/66055425822758f2575de50d7e82b371bb81370c/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/nearby/modules/tekhistory/DefaultTEKHistoryProvider.kt#L157

ので、この BroadcastReceiver 自体にはなくても良いように思います。

**Comment by keiji** [comment]
@tmurakami 
ありがとうございます。たしかに10秒の縛りは大きいですね。ということで、JobSchedulerを使う方式（ #91 ）にしました。
Backoffをしたり、再起動時にリスケジュールをしたりはやり過ぎかとも思うので、オプションで外から与えられるようにしたいところです（iOSとの兼ね合いを見ながらやります）。

またPreAuthorized APIを使う場合は動的にBroadcastReceiverを登録するようにしました。`PreAuthorizeReleasePhoneUnlockedBroadcastReceiver.OnReceive`を`TaskCompletionSource`で待ち受けるようにしています。

**Comment by tmurakami** [comment]
遅れてしまい申し訳ありません。

修正内容ですが、大きくは問題ないように思います。
少し気になる点といえば

- `GoAsync()`は無くても良い気がします
- `RequestPreAuthorizedTemporaryExposureKeyReleaseAsync()`は JobScheduler を使わなくても良い気がします

というところです。
(私が読み誤っているかもしれませんが...)

それと JobScheduler を使わないようにする方法について、遅くなってしまったのでどうしようか迷ったのですが、一応 2 案ほど思いついたので、以下に示しておきます。

#### 1. API 呼び出しを Handler 側で行ってもらうようにする

例えば

```csharp
interface IExposureDetection {
    
    Task<ExposureSummary> GetExposureSummary();
    
    Task<List<ExposureInformation>> GetExposureInformations();
    
    ...

}
```

といった感じのインタフェースの実装を各プラットフォームで用意して、それを Handler の引数に渡す方法です。
こうすればサマリ取得等の API 呼び出しを BroadcastReceiver 側から Handler 実装側に持っていくことができるので、Cappuccino 側で JobScheduler を使わなくとも良くなるのかなと思います。

#### 2. token と対になる TaskCompletionSource を用意して BroadcastReceiver で更新する

token と TaskCompletionSource の ConcurrentDictionary を Client に持っておいて、BroadcastReceiver 側で token (ExposureWindow モードの場合は適当な文字列) に対応する TaskCompletionSource を`SetResult()`する方法です。
(`GetReleasedTemporaryExposureKeys()`でやっているような感じです)
BroadcastReceiver 側ではブール値なり action 名なりを TaskCompletionSource にセットするだけになると思うので、BroadcastReceiver 自体の生存期間が短くても (`ProvideDiagnosisKeysAsync()`の呼び出し元が生存していれば良いと思うので) 問題ないかなと思っています。

この方式であれば、工夫すれば`ProvideDiagnosisKeysAsync()`の戻り値としてサマリ情報等を返す、なんてこともできるかもしれません。

懸念点としては、`provideDiagnosisKeys()`を呼んでから TaskCompletionSource が更新されるまでの間にアプリが kill されたりする (`provideDiagnosisKeys()`のタイムアウトは 60 分) と、結果が取得できなくなる点です。
ただ、それは iOS の`detectExposures()`も同じなのでは？ とも思うので、気にしなくても良いのかもしれません。
何れにせよ、呼び出し側では最後にチェックしたキーのタイムスタンプなりを保存するだろうと思うので、結果が取得できなかったとしても呼び出し側でリカバリーできるかなとは思います。

参考になれば幸いです。
